name: dhs
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - setuptools
  - pip:
    - torch==2.1.0
    - torchvision==0.16.0
    - tensorboard
    - tensorboardx
    - numpy>=1.21,<2.0
    - scikit-image
    - pandas
    - scipy
    - networkx
    - lxml
    - sacred==0.8.1
    - pretrainedmodels==0.7.4
    - opencv-python-headless>=4.5
    - PyYaml
    - frozendict==2.0.6
    - albumentations==0.5.2
    - shapely
    - tqdm
    - requests
    - pytest==6.2.5
    - scikit-learn